# Homework week 1

In [1]:
import pandas as pd
import numpy as np

## Question 1
What's the version of Pandas that you installed?

You can get the version information using the __version__ field:

In [2]:
pd.__version__

'1.5.3'

# Getting the data
For this homework, we'll use the California Housing Prices dataset. Download it from here.

You can do it with wget:

In [3]:
df = pd.read_csv('housing.csv')

In [4]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [5]:
df.tail()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND

## Question 2
How many columns are in the dataset?

In [6]:
print(f"The dataset has a total of {len(df.columns)} columns")

The dataset has a total of 10 columns


## Question 3
Which columns in the dataset have missing values?

In [7]:
list_of_null_columns = df.columns[df.isna().any()].tolist()

In [8]:
print(f'The columns that have missing values are: {list_of_null_columns}')

The columns that have missing values are: ['total_bedrooms']


## Question 4
How many unique values does the ocean_proximity column have?

In [9]:
print(f'The column ocean_proximity has {df.ocean_proximity.nunique()} unique values')
print(f'The unique values are {df.ocean_proximity.unique()}.')

The column ocean_proximity has 5 unique values
The unique values are ['NEAR BAY' '<1H OCEAN' 'INLAND' 'NEAR OCEAN' 'ISLAND'].


## Question 5
What's the average value of the median_house_value for the houses located near the bay?

In [10]:
df.median_house_value.mean()

206855.81690891474

In [11]:
df_near_bay = df[df['ocean_proximity'] == 'NEAR BAY']
df_median_house_value_average = df_near_bay.median_house_value.mean().round()

In [12]:
print(f'The average value of the median_house_value for the houses located near the bay is: {df_median_house_value_average}')

The average value of the median_house_value for the houses located near the bay is: 259212.0


## Question 6
- Calculate the average of total_bedrooms column in the dataset.
- Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
- Now, calculate the average of total_bedrooms again.
- Has it changed?

In [13]:
average_of_total_beadrooms =  df.total_bedrooms.mean().round()
average_of_total_beadrooms

538.0

In [14]:
df.fillna(df['total_bedrooms'].mean().round(), inplace=True)

In [15]:
new_average_of_total_beadrooms =  df.total_bedrooms.mean().round()
new_average_of_total_beadrooms

538.0

In [16]:
print(f'The average valeu remained the same: {new_average_of_total_beadrooms}')

The average valeu remained the same: 538.0


## Question 7
- Select all the options located on islands.
- Select only columns housing_median_age, total_rooms, total_bedrooms.
- Get the underlying NumPy array. Let's call it X.
- Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
- Compute the inverse of XTX.
- Create an array y with values [950, 1300, 800, 1000, 1300].
- Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
- What's the value of the last element of w?

In [17]:
df_island_located = df[df['ocean_proximity'] == 'ISLAND']
df_island_located

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318          ISLAND

In [18]:
df_island_located = df_island_located[['housing_median_age', 'total_rooms', 'total_bedrooms']]
df_island_located

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [20]:
X = np.array(df_island_located)
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [22]:
X_transpose = X.T
X_transpose

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

In [23]:
XTX = np.dot(X_transpose, X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [24]:
inverse_XTX = np.linalg.inv(XTX)
inverse_XTX

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [26]:
y = np.array([950, 1300, 800, 1000, 1300])
y

array([ 950, 1300,  800, 1000, 1300])

In [27]:
z = np.dot(inverse_XTX, X_transpose)
z

array([[-0.00825608, -0.00653208, -0.00232159,  0.02565144,  0.01204934],
       [-0.00165852,  0.0011141 ,  0.00139656, -0.00103215, -0.00110698],
       [ 0.00754365, -0.00301964, -0.00455125,  0.00181685,  0.00329418]])

In [29]:
w = np.dot(z,y)
w

array([23.12330961, -1.48124183,  5.69922946])

In [32]:
w[-1]

5.6992294550655656